#! /bin/sh
##
# @brief Change LCD brightness
#
#        Change the brightness of the current LCD via command line.
#        You should be a root to run this script.
#
# @usage
#   ./brt value
# 
# @param value 
#    A relative brightness. The max brightness is when value = 100.
#    If value > 100, it is regarded as value = 100. The minimum
#    brightness is set when value = 0. But this means a LCD blackout.
#    Thus, value smaller than 20 is ignored and set value = 20.
#    Non-numeric input is regarded as value = 20. 

# add H.Y
PREFIX="/sys/class/backlight/amdgpu_bl0"

MAX_V=$(cat ${PREFIX}/max_brightness)
CUR_V=$(cat ${PREFIX}/brightness)
CUR_R=$(echo "scale=1; ${CUR_V} * 100 / ${MAX_V}" | bc)

##
usage () {
  echo "usage:" >&2
  echo "   brt value" >&2
  echo "   value is an integer number between 20 and 100." >&2
  echo "   " >&2
  echo "   current brightness is " ${CUR_V}"/"${MAX_V} "=" ${CUR_R} "%" >&2
  exit 1;
}

## No argument, then show usage and exit. 
[ -z "${@}" ] && usage

## Parse the first argument. Non-numeric input is zero.
VALUE=$(echo ${1:?} | awk '{print $1*1}')
[ ${VALUE} -gt 100 ] && VALUE=100
[ ${VALUE} -lt  20 ] && VALUE=20

VALUE=$(echo "${MAX_V} * ${VALUE} / 100" | bc)

echo ${VALUE} | sudo tee ${PREFIX}/brightness >/dev/null

